<a href="https://colab.research.google.com/github/sujitx-vs/PGCP-AI_PML/blob/main/Day1_PML.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## PML

- > Food Ordering System.

- list : Hetrogenous , ordered ,mutable and duplicate allowed.

In [ ]:
ordered_items = ["Pizza","Burger","Pasta","Noodles","Broast"]
ordered_items

['Pizza', 'Burger', 'Pasta', 'Noodles', 'Broast']

In [ ]:
ordered_items.extend(["pepsi","fries"])
ordered_items

['Pizza', 'Burger', 'Pasta', 'Noodles', 'Broast', 'pepsi', 'fries']

In [ ]:
ordered_items.remove("Pizza")

In [ ]:
ordered_items

['Burger', 'Pasta', 'Noodles', 'Broast', 'pepsi', 'fries']

In [ ]:
ordered_items.pop()

'fries'

In [ ]:
ordered_items

['Burger', 'Pasta', 'Noodles', 'Broast', 'pepsi']

In [ ]:
ordered_items.pop(1)

'Pasta'

In [ ]:
print(ordered_items)

['Burger', 'Noodles', 'Broast', 'pepsi']

In [ ]:
ordered_items[:-1]

['Burger', 'Noodles', 'Broast']

In [ ]:
ordered_items1 =[]
for i in ordered_items:
  ordered_items1.append(i.upper())

In [ ]:
i.upper()

'PEPSI'

In [ ]:
upper_case = [item.upper() for item in ordered_items]

In [ ]:
upper_case

['BURGER', 'NOODLES', 'BROAST', 'PEPSI']

In [ ]:
ordered_items1

['BURGER', 'NOODLES', 'BROAST', 'PEPSI']

### Dict

  - key,value, hetrogenous,no order,mutable and duplicate key not allowed.

In [ ]:
customer = {"name":"Raj",
            "age":23,
            "city":"Mumbai"}

In [ ]:
customer

{'name': 'Raj', 'age': 23, 'city': 'Mumbai'}

In [ ]:
customer['name']

'Raj'

In [ ]:
customer.get("city")

'Mumbai'

In [ ]:
customer["phone"]= 908786578

In [ ]:
customer

{'name': 'Raj', 'age': 23, 'city': 'Mumbai', 'phone': 908786578}

In [ ]:
customer.update()

In [ ]:
customer.pop("city")

'Mumbai'

In [ ]:
customer.popitem()

('phone', 908786578)

In [ ]:
del(customer["age"])

In [ ]:
customer

{'name': 'Raj'}

### Sets
  - unorderd,Unique,no duplicate values, not mutable.

In [ ]:
cusines = {"indian","chinese","indian","japanese","korean","japanese"}

In [ ]:
cusines

{'chinese', 'indian', 'japanese', 'korean'}

In [ ]:
cusines.discard("chinese")

In [ ]:
cusines.add("mexican")

In [ ]:
cusines = cusines.union({"chinese","spanish","french"})

In [ ]:
set = cusines.intersection({"chinese","spanish","french"})
set

{'chinese', 'french', 'spanish'}

In [ ]:
cusines

{'chinese', 'french', 'indian', 'japanese', 'korean', 'mexican', 'spanish'}

### tuples

  - immutable,orderd

In [ ]:
location = (19.0700,72.8777)
lat, lon = location
print(lat,lon)

19.07 72.8777

unpacking

In [ ]:
t =(1,)# single value tuple, comma is compulsory to use single value tuple.

### Orderd dict with list, set, dict, tuple

In [ ]:
order = {
    "order_id": 101,
    "Customer":{
        "name":"Rahul",
        "age":22,
        "city":"Mumbai"
    },
    "items":["Pizza","Burger","Coke"],
    "cuisines":{"Italian","Indian"},
    "location":(19.0766,72.8777)
}

In [ ]:
order

{'order_id': 101,
 'Customer': {'name': 'Rahul', 'age': 22, 'city': 'Mumbai'},
 'items': ['Pizza', 'Burger', 'Coke'],
 'cuisines': {'Indian', 'Italian'},
 'location': (19.0766, 72.8777)}

In [ ]:
order['Customer']['name']

'Rahul'

In [ ]:
order['items']

['Pizza', 'Burger', 'Coke']

In [ ]:
order['cuisines'].add("mexican")
order

{'order_id': 101,
 'Customer': {'name': 'Rahul', 'age': 22, 'city': 'Mumbai'},
 'items': ['Pizza', 'Burger', 'Coke'],
 'cuisines': {'Indian', 'Italian', 'mexican'},
 'location': (19.0766, 72.8777)}

In [ ]:
del(order['Customer']['age'])
order

{'order_id': 101,
 'Customer': {'name': 'Rahul', 'city': 'Mumbai'},
 'items': ['Pizza', 'Burger', 'Coke'],
 'cuisines': {'Indian', 'Italian', 'mexican'},
 'location': (19.0766, 72.8777)}

In [ ]:
# order['Customer'].pop('age')

In [ ]:
order

{'order_id': 101,
 'Customer': {'name': 'Rahul', 'city': 'Mumbai'},
 'items': ['Pizza', 'Burger', 'Coke'],
 'cuisines': {'Indian', 'Italian', 'mexican'},
 'location': (19.0766, 72.8777)}

In [ ]:
order['items'].remove("Burger")

In [ ]:
order

{'order_id': 101,
 'Customer': {'name': 'Rahul', 'city': 'Mumbai'},
 'items': ['Pizza', 'Coke'],
 'cuisines': {'Indian', 'Italian', 'mexican'},
 'location': (19.0766, 72.8777)}

In [ ]:
order['items'].extend(["French fries","Chai","Ice cream"])

In [ ]:
order

{'order_id': 101,
 'Customer': {'name': 'Rahul', 'city': 'Mumbai'},
 'items': ['Pizza', 'Coke', 'French fries', 'Chai', 'Ice cream'],
 'cuisines': {'Indian', 'Italian', 'mexican'},
 'location': (19.0766, 72.8777)}

In [ ]:
import pandas as pd
dtypes = pd.DataFrame({
    'Type': ['int8', 'uint8', 'int16', 'uint16', 'int32', 'uint32',
             'int64', 'uint64', 'float16', 'float32', 'float64',
             'float128', 'complex64', 'complex128', 'bool',
             'object', 'string_', 'unicode_'],
    'Type Code': ['i1', 'u1', 'i2', 'u2', 'i4', 'u4',
                  'i8', 'u8', 'f2', 'f4 or f', 'f8 or d',
                  'f16 or g', 'c8', 'c16', '',
                  'O', 'S', 'U']
})

In [ ]:
dtypes

          Type Type Code
0         int8        i1
1        uint8        u1
2        int16        i2
3       uint16        u2
4        int32        i4
5       uint32        u4
6        int64        i8
7       uint64        u8
8      float16        f2
9      float32   f4 or f
10     float64   f8 or d
11    float128  f16 or g
12   complex64        c8
13  complex128       c16
14        bool
15      object         O
16     string_         S
17    unicode_         U

In [ ]:
import numpy as np

In [ ]:
arr = np.array([12,3,4,5],dtype="f4")
arr

array([12.,  3.,  4.,  5.], dtype=float32)

In [ ]:
arr.dtype

dtype('float32')

In [ ]:
np.array([1+2j,2-4j],dtype = np.complex64)

array([1.+2.j, 2.-4.j], dtype=complex64)

In [ ]:
ar= np.array([1.+2.j, 2.-4.j], dtype=np.complex128)
ar.dtype

dtype('complex128')

In [ ]:
np.array([0,1,1],dtype=np.bool_)

array([False,  True,  True])

In [ ]:
np.array([0,1,1],dtype = np.bool)

array([False,  True,  True])

In [ ]:
np.array(['abc','cde'],dtype='S3')

array([b'abc', b'cde'], dtype='|S3')

In [ ]:
np.array([12,34,56],dtype='i2')

array([12, 34, 56], dtype=int16)

In [ ]:
a = pd.Series([1,"Amit",3.5,'Hello'])

In [ ]:
a

0        1
1     Amit
2      3.5
3    Hello
dtype: object

In [ ]:
d = {
     "Sam":12000,
     "ram":5000,
     "tom":45000,
     "jim":50000}

In [ ]:
pd.Series(d)

Sam    12000
ram     5000
tom    45000
jim    50000
dtype: int64

Dataframe- 2D combination of rows & Columns

In [ ]:
student ={
    "Name":["Amit","Bob","Tom"],
    "Marks":[78,56,89]
}

df= pd.DataFrame(student)

In [ ]:
df

   Name  Marks
0  Amit     78
1   Bob     56
2   Tom     89

In [ ]:
df["Grade"]=["A","B","C"]

In [ ]:
df

   Name  Marks Grade
0  Amit     78     A
1   Bob     56     B
2   Tom     89     C

In [ ]:
df = df.drop("Grade",axis = 1)

In [ ]:
df

   Name  Marks
0  Amit     78
1   Bob     56
2   Tom     89

In [ ]:
df.rename(columns = {"Name":'Title'},inplace=True)
df

  Title  Marks
0  Amit     78
1   Bob     56
2   Tom     89

In [ ]:
df["Marks"]= df["Marks"].apply(lambda x:x+5)
df

  Title  Marks
0  Amit     83
1   Bob     61
2   Tom     94

In [ ]:
df
new_data = pd.DataFrame({
    'Title': ['Ram', 'Raju','Kesu'],
    'Marks': [82, 78,93]

})

df = pd.concat([df, new_data], ignore_index=True)

In [ ]:
df

  Title  Marks
0  Amit     83
1   Bob     61
2   Tom     94
3   Ram     82
4  Raju     78
5  Kesu     93

In [ ]:
# lambda function to find the marks greater than 90 or less than 76.

In [ ]:
[c for c in df["Marks"] if c >90]

[94, 93]

In [ ]:
filtered_df = df[(df['Marks'] > 90) | (df['Marks'] < 76)]

In [ ]:
filtered_df

  Title  Marks
1   Bob     61
2   Tom     94
5  Kesu     93