<a href="https://colab.research.google.com/github/sujitx-vs/PGCP-AI_PML/blob/main/Day3_PML.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np

In [ ]:
data = {
    'Income': [50000, 60000, 55000, np.nan, 65000],
    'Gender': ['Male', 'Female', 'Female', 'Male', np.nan],
    'City': ['Mumbai', 'Delhi', 'Mumbai', 'Chennai', 'Delhi'],
    'Signup_Date': ['2022-01-01', '2021-06-15', '2022-03-10', '2020-12-20', '2021-08-05'],
    'Last_Login': ['2023-01-01', '2023-02-10', '2023-01-15', '2023-01-20', '2023-02-01'],
    'Purchased': [1, 0, 1, 0, 1]
}

df = pd.DataFrame(data)
df

    Income  Gender     City Signup_Date  Last_Login  Purchased
0  50000.0    Male   Mumbai  2022-01-01  2023-01-01          1
1  60000.0  Female    Delhi  2021-06-15  2023-02-10          0
2  55000.0  Female   Mumbai  2022-03-10  2023-01-15          1
3      NaN    Male  Chennai  2020-12-20  2023-01-20          0
4  65000.0     NaN    Delhi  2021-08-05  2023-02-01          1

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 6 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Income       4 non-null      float64
 1   Gender       4 non-null      object
 2   City         5 non-null      object
 3   Signup_Date  5 non-null      object
 4   Last_Login   5 non-null      object
 5   Purchased    5 non-null      int64
dtypes: float64(1), int64(1), object(4)
memory usage: 372.0+ bytes

In [ ]:
df.describe()

             Income  Purchased
count      4.000000   5.000000
mean   57500.000000   0.600000
std     6454.972244   0.547723
min    50000.000000   0.000000
25%    53750.000000   0.000000
50%    57500.000000   1.000000
75%    61250.000000   1.000000
max    65000.000000   1.000000

In [ ]:
df.isna().sum()

Income         1
Gender         1
City           0
Signup_Date    0
Last_Login     0
Purchased      0
dtype: int64

In [ ]:
df['Signup_Date'] = pd.to_datetime(df['Signup_Date'])
df['Last_Login'] = pd.to_datetime(df['Last_Login'])

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 6 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Income       4 non-null      float64
 1   Gender       4 non-null      object
 2   City         5 non-null      object
 3   Signup_Date  5 non-null      datetime64[ns]
 4   Last_Login   5 non-null      datetime64[ns]
 5   Purchased    5 non-null      int64
dtypes: datetime64[ns](2), float64(1), int64(1), object(2)
memory usage: 372.0+ bytes

In [ ]:
# 1. Handling Missing Values.
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import LabelEncoder, OneHotEncoder, StandardScaler

#SimpleImputer.

#Numerical column

imputer = SimpleImputer(strategy = "mean")
df['Income'] = imputer.fit_transform(df[['Income']])

In [ ]:
df

    Income  Gender     City Signup_Date Last_Login  Purchased
0  50000.0    Male   Mumbai  2022-01-01 2023-01-01          1
1  60000.0  Female    Delhi  2021-06-15 2023-02-10          0
2  55000.0  Female   Mumbai  2022-03-10 2023-01-15          1
3  57500.0    Male  Chennai  2020-12-20 2023-01-20          0
4  65000.0     NaN    Delhi  2021-08-05 2023-02-01          1

In [ ]:
#Categorical Column
imputer_cat = SimpleImputer(strategy = "most_frequent")
df['Gender'] = imputer_cat.fit_transform(df[['Gender']]).ravel()
df

    Income  Gender     City Signup_Date  Last_Login  Purchased
0  50000.0    Male   Mumbai  2022-01-01  2023-01-01          1
1  60000.0  Female    Delhi  2021-06-15  2023-02-10          0
2  55000.0  Female   Mumbai  2022-03-10  2023-01-15          1
3      NaN    Male  Chennai  2020-12-20  2023-01-20          0
4  65000.0  Female    Delhi  2021-08-05  2023-02-01          1

In [ ]:
#Data Feature Engineering.

df['Signup_Year'] = df['Signup_Date'].dt.year
df['Signup_Month'] = df['Signup_Date'].dt.month

In [ ]:
df

,Income,Gender,City,Signup_Date,Last_Login,Purchased,Signup_Year,Signup_Month
0,50000.0,Male,Mumbai,2022-01-01,2023-01-01,1,2022,1
1,60000.0,Female,Delhi,2021-06-15,2023-02-10,0,2021,6
2,55000.0,Female,Mumbai,2022-03-10,2023-01-15,1,2022,3
3,57500.0,Male,Chennai,2020-12-20,2023-01-20,0,2020,12
4,65000.0,Female,Delhi,2021-08-05,2023-02-01,1,2021,8

In [ ]:
df["Tenure_Days"] = (df['Last_Login']-df['Signup_Date']).dt.days

In [ ]:
df

,Income,Gender,City,Signup_Date,Last_Login,Purchased,Signup_Year,Signup_Month,Tenure_Days
0,50000.0,Male,Mumbai,2022-01-01,2023-01-01,1,2022,1,365
1,60000.0,Female,Delhi,2021-06-15,2023-02-10,0,2021,6,605
2,55000.0,Female,Mumbai,2022-03-10,2023-01-15,1,2022,3,311
3,57500.0,Male,Chennai,2020-12-20,2023-01-20,0,2020,12,761
4,65000.0,Female,Delhi,2021-08-05,2023-02-01,1,2021,8,545

In [ ]:
#Onehot encoding

encoder = OneHotEncoder()
city = encoder.fit_transform(df[['City']])

city_df = pd.DataFrame(city.toarray(),columns=encoder.get_feature_names_out(['City']))
df = pd.concat([df,city_df],axis = 1)

In [ ]:
df

,Income,Gender,City,Signup_Date,Last_Login,Purchased,Signup_Year,Signup_Month,Tenure_Days,City_Chennai,City_Delhi,City_Mumbai
0,50000.0,Male,Mumbai,2022-01-01,2023-01-01,1,2022,1,365,0.0,0.0,1.0
1,60000.0,Female,Delhi,2021-06-15,2023-02-10,0,2021,6,605,0.0,1.0,0.0
2,55000.0,Female,Mumbai,2022-03-10,2023-01-15,1,2022,3,311,0.0,0.0,1.0
3,57500.0,Male,Chennai,2020-12-20,2023-01-20,0,2020,12,761,1.0,0.0,0.0
4,65000.0,Female,Delhi,2021-08-05,2023-02-01,1,2021,8,545,0.0,1.0,0.0

In [ ]:
#feature Scaling

scalar = StandardScaler()
df[['Income_1']] = scalar.fit_transform(df[['Income']])

In [ ]:
df

,Income,Gender,City,Signup_Date,Last_Login,Purchased,Signup_Year,Signup_Month,Tenure_Days,City_Chennai,City_Delhi,City_Mumbai,Income_1
0,50000.0,Male,Mumbai,2022-01-01,2023-01-01,1,2022,1,365,0.0,0.0,1.0,-1.5
1,60000.0,Female,Delhi,2021-06-15,2023-02-10,0,2021,6,605,0.0,1.0,0.0,0.5
2,55000.0,Female,Mumbai,2022-03-10,2023-01-15,1,2022,3,311,0.0,0.0,1.0,-0.5
3,57500.0,Male,Chennai,2020-12-20,2023-01-20,0,2020,12,761,1.0,0.0,0.0,0.0
4,65000.0,Female,Delhi,2021-08-05,2023-02-01,1,2021,8,545,0.0,1.0,0.0,1.5

In [ ]:
#Feature Transform
df['Income_log'] = np.log1p(df['Income'])

In [ ]:
df

,Income,Gender,City,Signup_Date,Last_Login,Purchased,Signup_Year,Signup_Month,Tenure_Days,City_Chennai,City_Delhi,City_Mumbai,Income_1,Income_log
0,50000.0,Male,Mumbai,2022-01-01,2023-01-01,1,2022,1,365,0.0,0.0,1.0,-1.5,10.819798
1,60000.0,Female,Delhi,2021-06-15,2023-02-10,0,2021,6,605,0.0,1.0,0.0,0.5,11.002117
2,55000.0,Female,Mumbai,2022-03-10,2023-01-15,1,2022,3,311,0.0,0.0,1.0,-0.5,10.915107
3,57500.0,Male,Chennai,2020-12-20,2023-01-20,0,2020,12,761,1.0,0.0,0.0,0.0,10.959558
4,65000.0,Female,Delhi,2021-08-05,2023-02-01,1,2021,8,545,0.0,1.0,0.0,1.5,11.082158

#Pipelining

In [ ]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import LabelEncoder, OneHotEncoder, StandardScaler

from sklearn.linear_model import LogisticRegression
from sklearn.pipeline import Pipeline
from sklearn.compose import ColumnTransformer

from sklearn.model_selection import  train_test_split

In [ ]:
data = {
    'Income': [50000, 60000, 55000, np.nan, 65000],
    'Gender': ['Male', 'Female', 'Female', 'Male', np.nan],
    'City': ['Mumbai', 'Delhi', 'Mumbai', 'Chennai', 'Delhi'],
    'Signup_Date': ['2022-01-01', '2021-06-15', '2022-03-10', '2020-12-20', '2021-08-05'],
    'Last_Login': ['2023-01-01', '2023-02-10', '2023-01-15', '2023-01-20', '2023-02-01'],
    'Purchased': [1, 0, 1, 0, 1]
}

df = pd.DataFrame(data)
df

    Income  Gender     City Signup_Date  Last_Login  Purchased
0  50000.0    Male   Mumbai  2022-01-01  2023-01-01          1
1  60000.0  Female    Delhi  2021-06-15  2023-02-10          0
2  55000.0  Female   Mumbai  2022-03-10  2023-01-15          1
3      NaN    Male  Chennai  2020-12-20  2023-01-20          0
4  65000.0     NaN    Delhi  2021-08-05  2023-02-01          1

In [ ]:
num_col = ['Income']
cat_col = ["Gender","City"]

In [ ]:
from sklearn import pipeline
n_pipeline = Pipeline([
    ('imputer',SimpleImputer(strategy="mean")),
    ('scalar',StandardScaler())
])

c_pipeline = Pipeline([
    ('imputer',SimpleImputer(strategy="most_frequent")),
    ('encoder',OneHotEncoder(handle_unknown='ignore'))
])


preprocessor = ColumnTransformer(
    [
        ('num',n_pipeline,num_col),
        ("cat",c_pipeline)
    ]
)


pipeline = Pipeline([
    ('preprocessor',preprocessor),
    ('model', LogisticRegression())
])

#example 3, Datas.csv

In [ ]:
dataset = pd.read_csv('/content/datas..csv')

In [ ]:
dataset

   Country   Age   Salary Purchased
0   France  44.0  72000.0        No
1    Spain  27.0  48000.0       Yes
2  Germany  30.0  54000.0        No
3    Spain  38.0  61000.0        No
4  Germany  40.0      NaN       Yes
5   France  35.0  58000.0       Yes
6    Spain   NaN  52000.0        No
7   France  48.0  79000.0       Yes
8  Germany  50.0  83000.0        No
9   France  37.0  67000.0       Yes

In [ ]:
# Independent variable
X = dataset.iloc[:,:-1].values

# Dependent Variable
Y = dataset.iloc[:,-1].values

In [ ]:
X

array([['France', 44.0, 72000.0],
       ['Spain', 27.0, 48000.0],
       ['Germany', 30.0, 54000.0],
       ['Spain', 38.0, 61000.0],
       ['Germany', 40.0, nan],
       ['France', 35.0, 58000.0],
       ['Spain', nan, 52000.0],
       ['France', 48.0, 79000.0],
       ['Germany', 50.0, 83000.0],
       ['France', 37.0, 67000.0]], dtype=object)

In [ ]:
from sklearn.impute import SimpleImputer

imputer = SimpleImputer(missing_values=np.nan,strategy="mean")
imputer = imputer.fit(X[:,1:3])
X[:,1:3]= imputer.transform(X[:,1:3])

In [ ]:
X

array([['France', 44.0, 72000.0],
       ['Spain', 27.0, 48000.0],
       ['Germany', 30.0, 54000.0],
       ['Spain', 38.0, 61000.0],
       ['Germany', 40.0, 63777.77777777778],
       ['France', 35.0, 58000.0],
       ['Spain', 38.77777777777778, 52000.0],
       ['France', 48.0, 79000.0],
       ['Germany', 50.0, 83000.0],
       ['France', 37.0, 67000.0]], dtype=object)

In [ ]:
# Encoder Categoriccal data

from sklearn.preprocessing import LabelEncoder, OneHotEncoder
from sklearn.compose import ColumnTransformer

label = LabelEncoder()

X[:,0]= label.fit_transform(X[:,0])

In [ ]:
X

array([[0, 44.0, 72000.0],
       [2, 27.0, 48000.0],
       [1, 30.0, 54000.0],
       [2, 38.0, 61000.0],
       [1, 40.0, 63777.77777777778],
       [0, 35.0, 58000.0],
       [2, 38.77777777777778, 52000.0],
       [0, 48.0, 79000.0],
       [1, 50.0, 83000.0],
       [0, 37.0, 67000.0]], dtype=object)

In [ ]:
col_trans = ColumnTransformer([
    ('encoder',OneHotEncoder(),[0])
],remainder='passthrough')

X = col_trans.fit_transform(X)

In [ ]:
X

array([[1.0, 0.0, 0.0, 44.0, 72000.0],
       [0.0, 0.0, 1.0, 27.0, 48000.0],
       [0.0, 1.0, 0.0, 30.0, 54000.0],
       [0.0, 0.0, 1.0, 38.0, 61000.0],
       [0.0, 1.0, 0.0, 40.0, 63777.77777777778],
       [1.0, 0.0, 0.0, 35.0, 58000.0],
       [0.0, 0.0, 1.0, 38.77777777777778, 52000.0],
       [1.0, 0.0, 0.0, 48.0, 79000.0],
       [0.0, 1.0, 0.0, 50.0, 83000.0],
       [1.0, 0.0, 0.0, 37.0, 67000.0]], dtype=object)

In [ ]:
label1 = LabelEncoder()
Y = label1.fit_transform(Y)

In [ ]:
Y

array([0, 1, 0, 0, 1, 1, 0, 1, 0, 1])

In [ ]:
from sklearn.model_selection import train_test_split

In [ ]:
x_train,x_test,y_train,y_test = train_test_split(X,Y,test_size=.2,random_state=42)

In [ ]:
x_train

array([[1.0, 0.0, 0.0, 35.0, 58000.0],
       [1.0, 0.0, 0.0, 44.0, 72000.0],
       [1.0, 0.0, 0.0, 48.0, 79000.0],
       [0.0, 1.0, 0.0, 30.0, 54000.0],
       [1.0, 0.0, 0.0, 37.0, 67000.0],
       [0.0, 1.0, 0.0, 40.0, 63777.77777777778],
       [0.0, 0.0, 1.0, 38.0, 61000.0],
       [0.0, 0.0, 1.0, 38.77777777777778, 52000.0]], dtype=object)

In [ ]:
x_test

array([[0.0, 1.0, 0.0, 50.0, 83000.0],
       [0.0, 0.0, 1.0, 27.0, 48000.0]], dtype=object)

In [ ]:
y_train

array([1, 0, 1, 0, 1, 1, 0, 0])

In [ ]:
y_test

array([0, 1])

In [ ]:
sc = StandardScaler()
x_train = sc.fit_transform(x_train)
x_test = sc.fit_transform(x_test)

In [ ]:
x_train

array([[ 1.        , -0.57735027, -0.57735027, -0.7529426 , -0.62603778],
       [ 1.        , -0.57735027, -0.57735027,  1.00845381,  1.01304295],
       [ 1.        , -0.57735027, -0.57735027,  1.79129666,  1.83258331],
       [-1.        ,  1.73205081, -0.57735027, -1.73149616, -1.09434656],
       [ 1.        , -0.57735027, -0.57735027, -0.36152118,  0.42765698],
       [-1.        ,  1.73205081, -0.57735027,  0.22561096,  0.05040824],
       [-1.        , -0.57735027,  1.73205081, -0.16581046, -0.27480619],
       [-1.        , -0.57735027,  1.73205081, -0.01359102, -1.32850095]])

In [ ]:
x_test

array([[ 0.,  1., -1.,  1.,  1.],
       [ 0., -1.,  1., -1., -1.]])